theme: jekyll-theme-minimal
title: pistoletpierre.github.io
description: test123
logo: [Location of the logo]
show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]

#title: Minimal theme
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
