theme: jekyll-theme-minimal
title: pistoletpierre.github.io
description: test123
logo: https://github.com/pages-themes/minimal/raw/master/assets/img/logo.png
show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]
github:
  zip_url: http://example.com/download.zip
  tar_url: http://example.com/download.zip
  repository_url: https://github.com/pistoletpierre/language-systemverilog

#title: Minimal theme
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal

#https://github.com/pages-themes/minimal
#https://github.com/pages-themes/minimal/blob/master/_layouts/default.html
